Repository aiven/aiven-operator, pull requests merged in 2023-11, with the labels that each got.

#534 feat(docs): add string format
  CHANGELOG.md
  docs/docs/api-reference/cassandra.md
  docs/docs/api-reference/clickhouse.md
  docs/docs/api-reference/clickhouseuser.md
  docs/docs/api-reference/connectionpool.md
  docs/docs/api-reference/database.md
  docs/docs/api-reference/grafana.md
  docs/docs/api-reference/kafka.md
  docs/docs/api-reference/kafkaacl.md
  docs/docs/api-reference/kafkaconnect.md
  docs/docs/api-reference/kafkaconnector.md
  docs/docs/api-reference/kafkaschema.md
  docs/docs/api-reference/kafkatopic.md
  docs/docs/api-reference/mysql.md
  docs/docs/api-reference/opensearch.md
  docs/docs/api-reference/postgresql.md
  docs/docs/api-reference/projectvpc.md
  docs/docs/api-reference/redis.md
  docs/docs/api-reference/serviceintegration.md
  docs/docs/api-reference/serviceuser.md
  generators/docs/generator.go
Labels: documentation

#526 fix(service_intergration): empty user config to API convertion
  controllers/common.go
  controllers/serviceintegration_controller.go
Labels: bug

#536 feat(release): CRD changelog generator
  CHANGELOG.md
  docs/docs/contributing/resource-generation.md
  generators/charts/changelog.go
  generators/charts/changelog_test.go
  generators/charts/crds.go
  generators/charts/main.go
  generators/charts/version.go
Labels: enhancement

#540 chore(project): skip the project test
  tests/project_test.go
Labels: enhancement

#539 chore(release): v0.15.0
  CHANGELOG.md
  charts/aiven-operator-crds/Chart.yaml
  charts/aiven-operator/Chart.yaml
  docs/docs/changelog.md
Labels: release

#545 fix(ci): use go1.21 in Dockerfile
  Dockerfile
Labels: bug

#547 feat: implement error-conditions
  controllers/basic_controller.go
  controllers/common.go
  controllers/connectionpool_controller.go
  controllers/database_controller.go
  controllers/generic_service_handler.go
  controllers/kafkaacl_controller.go
  controllers/kafkaconnector_controller.go
  controllers/kafkatopic_controller.go
  controllers/project_controller.go
Labels: enhancement

#555 docs: link to prereqs from installation instructions
  docs/docs/installation/helm.md
  docs/docs/installation/kubectl.md
Labels: documentation
