Repository aiven/aiven-operator, pull requests merged in 2023-05, with the labels that each got.

#384 feat: update service tags when creating or updating a service
  controllers/generic_service_handler.go
  tests/cassandra_test.go
  tests/clickhouse_test.go
  tests/grafana_test.go
  tests/kafka_test.go
  tests/mysql_test.go
  tests/opensearch_test.go
  tests/postgresql_test.go
  tests/redis_test.go
Labels: bug

#388 ci(release): sync charts as last step
  .github/workflows/release.yaml
Labels: enhancement

#389 refactor(tests): make test session reusable
  tests/cassandra_test.go
  tests/clickhouse_test.go
  tests/clickhouseuser_test.go
  tests/connectionpool_test.go
  tests/database_test.go
  tests/generic_service_handler_test.go
  tests/grafana_test.go
  tests/kafka_test.go
  tests/kafka_with_projectvpc_ref_test.go
  tests/kafkaacl_test.go
  tests/kafkaconnect_test.go
  tests/kafkaschema_test.go
  tests/kafkatopic_test.go
  tests/mysql_test.go
  tests/opensearch_test.go
  tests/postgresql_test.go
  tests/project_test.go
  tests/projectvpc_test.go
  tests/redis_test.go
  tests/serviceintegration_test.go
  tests/serviceuser_test.go
  tests/session.go
Labels: enhancement

#394 fix(secrets): add all permissions to finalizers
  CHANGELOG.md
  charts/aiven-operator/templates/cluster_role.yaml
  config/rbac/role.yaml
  controllers/cassandra_controller.go
  controllers/clickhouse_controller.go
  controllers/clickhouseuser_controller.go
  controllers/connectionpool_controller.go
  controllers/grafana_controller.go
  controllers/kafka_controller.go
  controllers/kafkaconnect_controller.go
  controllers/kafkaconnector_controller.go
  controllers/mysql_controller.go
  controllers/opensearch_controller.go
  controllers/postgresql_controller.go
  controllers/project_controller.go
  controllers/redis_controller.go
  controllers/serviceuser_controller.go
Labels: bug

#385 Allow overriding cloudName used in tests
  tests/cassandra_test.go
  tests/clickhouse_test.go
  tests/clickhouseuser_test.go
  tests/connectionpool_test.go
  tests/database_test.go
  tests/grafana_test.go
  tests/kafka_test.go
  tests/kafka_with_projectvpc_ref_test.go
  tests/kafkaacl_test.go
  tests/kafkaconnect_test.go
  tests/kafkaschema_test.go
  tests/kafkatopic_test.go
  tests/mysql_test.go
  tests/opensearch_test.go
  tests/postgresql_test.go
  tests/projectvpc_test.go
  tests/redis_test.go
  tests/serviceintegration_test.go
  tests/serviceuser_test.go
  tests/suite_test.go
Labels: enhancement

#393 feat: allow optional installation of cluster role
  CHANGELOG.md
  charts/aiven-operator/templates/cluster_role.yaml
  charts/aiven-operator/templates/cluster_role_binding.yaml
  charts/aiven-operator/values.yaml
  docs/docs/installation/helm.md
Labels: enhancement

#399 ci(commitlint): ignore dependabot's commit messages
  commitlint.config.js
Labels: enhancement

#398 chore(release): v0.12.0
  CHANGELOG.md
  charts/aiven-operator-crds/Chart.yaml
  charts/aiven-operator/Chart.yaml
  docs/docs/changelog.md
Labels: release

#402 chore(docs): remove nlbr extension
  api/v1alpha1/cassandra_types.go
  api/v1alpha1/clickhouse_types.go
  api/v1alpha1/clickhouseuser_types.go
  api/v1alpha1/connectionpool_types.go
  api/v1alpha1/grafana_types.go
  api/v1alpha1/kafka_types.go
  api/v1alpha1/mysql_types.go
  api/v1alpha1/opensearch_types.go
  api/v1alpha1/postgresql_types.go
  api/v1alpha1/project_types.go
  api/v1alpha1/redis_types.go
  api/v1alpha1/serviceuser_types.go
  charts/aiven-operator-crds/templates/aiven.io_cassandras.yaml
  charts/aiven-operator-crds/templates/aiven.io_clickhouses.yaml
  charts/aiven-operator-crds/templates/aiven.io_clickhouseusers.yaml
  charts/aiven-operator-crds/templates/aiven.io_connectionpools.yaml
  charts/aiven-operator-crds/templates/aiven.io_grafanas.yaml
  charts/aiven-operator-crds/templates/aiven.io_kafkas.yaml
  charts/aiven-operator-crds/templates/aiven.io_mysqls.yaml
  charts/aiven-operator-crds/templates/aiven.io_opensearches.yaml
  charts/aiven-operator-crds/templates/aiven.io_postgresqls.yaml
  charts/aiven-operator-crds/templates/aiven.io_projects.yaml
  charts/aiven-operator-crds/templates/aiven.io_redis.yaml
  charts/aiven-operator-crds/templates/aiven.io_serviceusers.yaml
  config/crd/bases/aiven.io_cassandras.yaml
  config/crd/bases/aiven.io_clickhouses.yaml
  config/crd/bases/aiven.io_clickhouseusers.yaml
  config/crd/bases/aiven.io_connectionpools.yaml
  config/crd/bases/aiven.io_grafanas.yaml
  config/crd/bases/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_mysqls.yaml
  config/crd/bases/aiven.io_opensearches.yaml
  config/crd/bases/aiven.io_postgresqls.yaml
  config/crd/bases/aiven.io_projects.yaml
  config/crd/bases/aiven.io_redis.yaml
  config/crd/bases/aiven.io_serviceusers.yaml
  docs/docs/api-reference/cassandra.md
  docs/docs/api-reference/clickhouse.md
  docs/docs/api-reference/clickhouseuser.md
  docs/docs/api-reference/connectionpool.md
  docs/docs/api-reference/grafana.md
  docs/docs/api-reference/kafka.md
  docs/docs/api-reference/mysql.md
  docs/docs/api-reference/opensearch.md
  docs/docs/api-reference/postgresql.md
  docs/docs/api-reference/project.md
  docs/docs/api-reference/redis.md
  docs/docs/api-reference/serviceuser.md
  docs/mkdocs.yml
Labels: enhancement

#415 ci(dependabot): ignore sigs.k8s.io/controller-runtime major/minor
  .github/dependabot.yml
Labels: enhancement
