Repository aiven/aiven-operator, pull requests merged in 2023-03, with the labels that each got.

#282 [bug]Setting config: min_cleanable_dirty_ratio: 0.1 does not apply
  controllers/kafkatopic_controller.go
  controllers/kafkatopic_controller_test.go
Labels: bug

#278 add new test suite
  .github/workflows/acceptance-tests.yaml
  .github/workflows/tests.yaml
  Makefile
  controllers/basic_controller.go
  controllers/common.go
  controllers/secret_finalizer_gc_controller.go
  controllers/setup.go
  controllers/suite_test.go
  docs/docs/api-reference/clickhouse.md
  docs/docs/api-reference/examples/clickhouse.yaml
  docs/docs/api-reference/examples/kafka.yaml
  docs/docs/api-reference/examples/kafkaconnect.yaml
  docs/docs/api-reference/kafka.md
  docs/docs/api-reference/kafkaconnect.md
  go.mod
  go.sum
  main.go
  tests/serviceintegration_test.go
  tests/suite.go
  tests/suite_test.go
Labels: enhancement

#281 add links to parent schemas
  docs/docs/api-reference/cassandra.md
  docs/docs/api-reference/clickhouse.md
  docs/docs/api-reference/clickhouseuser.md
  docs/docs/api-reference/connectionpool.md
  docs/docs/api-reference/database.md
  docs/docs/api-reference/grafana.md
  docs/docs/api-reference/kafka.md
  docs/docs/api-reference/kafkaacl.md
  docs/docs/api-reference/kafkaconnect.md
  docs/docs/api-reference/kafkaconnector.md
  docs/docs/api-reference/kafkaschema.md
  docs/docs/api-reference/kafkatopic.md
  docs/docs/api-reference/mysql.md
  docs/docs/api-reference/opensearch.md
  docs/docs/api-reference/postgresql.md
  docs/docs/api-reference/project.md
  docs/docs/api-reference/projectvpc.md
  docs/docs/api-reference/redis.md
  docs/docs/api-reference/serviceintegration.md
  docs/docs/api-reference/serviceuser.md
  docs_generator/main.go
Labels: documentation

#280 feat(kafkatopic): add topicName property
  .github/workflows/tests.yaml
  CHANGELOG.md
  Makefile
  api/v1alpha1/kafkatopic_types.go
  config/crd/bases/aiven.io_kafkatopics.yaml
  controllers/kafkatopic_controller.go
  docs/docs/api-reference/examples/kafkatopic.yaml
  docs/docs/api-reference/kafkatopic.md
  tests/kafkatopic_test.go
  tests/suite_test.go
Labels: enhancement, customer request

#285 feat: accept false value for termination_protection
  CHANGELOG.md
  README.md
  api/v1alpha1/cassandra_webhook.go
  api/v1alpha1/clickhouse_webhook.go
  api/v1alpha1/common.go
  api/v1alpha1/database_types.go
  api/v1alpha1/database_webhook.go
  api/v1alpha1/grafana_webhook.go
  api/v1alpha1/kafka_webhook.go
  api/v1alpha1/kafkaconnect_webhook.go
  api/v1alpha1/kafkatopic_types.go
  api/v1alpha1/kafkatopic_webhook.go
  api/v1alpha1/mysql_webhook.go
  api/v1alpha1/opensearch_webhook.go
  api/v1alpha1/postgresql_webhook.go
  api/v1alpha1/redis_webhook.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/common.go
  controllers/database_controller.go
  controllers/generic_service_handler.go
  controllers/kafkatopic_controller.go
Labels: enhancement

#286 chore(e2e): remove kafka after the test
  test/e2e/kafka-connector/connect-kafka-to-postgres/05-delete.yaml
Labels: enhancement

#288 fix(service): mark plan as a required field
  CHANGELOG.md
  api/v1alpha1/common.go
  config/crd/bases/aiven.io_cassandras.yaml
  config/crd/bases/aiven.io_clickhouses.yaml
  config/crd/bases/aiven.io_grafanas.yaml
  config/crd/bases/aiven.io_kafkaconnects.yaml
  config/crd/bases/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_mysqls.yaml
  config/crd/bases/aiven.io_opensearches.yaml
  config/crd/bases/aiven.io_postgresqls.yaml
  config/crd/bases/aiven.io_redis.yaml
  docs/docs/api-reference/cassandra.md
  docs/docs/api-reference/clickhouse.md
  docs/docs/api-reference/examples/kafka.yaml
  docs/docs/api-reference/grafana.md
  docs/docs/api-reference/kafka.md
  docs/docs/api-reference/kafkaconnect.md
  docs/docs/api-reference/mysql.md
  docs/docs/api-reference/opensearch.md
  docs/docs/api-reference/postgresql.md
  docs/docs/api-reference/redis.md
  docs_generator/validator.go
  test/e2e/kafka-topic/simple-kafka-topic/01-kafka.yaml
  test/e2e/kafka/kafka-simple-cluster/01-kafka.yaml
Labels: bug

#289 feat(validation): validate float minimum and maximum
  CHANGELOG.md
  api/v1alpha1/userconfig/service/mysql/mysql.go
  api/v1alpha1/userconfig/service/pg/pg.go
  config/crd/bases/aiven.io_mysqls.yaml
  config/crd/bases/aiven.io_postgresqls.yaml
  docs/docs/api-reference/mysql.md
  docs/docs/api-reference/postgresql.md
  userconfigs_generator/generator.go
Labels: enhancement

#309 feat(helm): add charts generator
  CHANGELOG.md
  Makefile
  charts/aiven-operator-crds/templates/aiven.io_cassandras.yaml
  charts/aiven-operator-crds/templates/aiven.io_clickhouses.yaml
  charts/aiven-operator-crds/templates/aiven.io_clickhouseusers.yaml
  charts/aiven-operator-crds/templates/aiven.io_connectionpools.yaml
  charts/aiven-operator-crds/templates/aiven.io_databases.yaml
  charts/aiven-operator-crds/templates/aiven.io_grafanas.yaml
  charts/aiven-operator-crds/templates/aiven.io_kafkaacls.yaml
  charts/aiven-operator-crds/templates/aiven.io_kafkaconnectors.yaml
  charts/aiven-operator-crds/templates/aiven.io_kafkaconnects.yaml
  charts/aiven-operator-crds/templates/aiven.io_kafkas.yaml
  charts/aiven-operator-crds/templates/aiven.io_kafkaschemas.yaml
  charts/aiven-operator-crds/templates/aiven.io_kafkatopics.yaml
  charts/aiven-operator-crds/templates/aiven.io_mysqls.yaml
  charts/aiven-operator-crds/templates/aiven.io_opensearches.yaml
  charts/aiven-operator-crds/templates/aiven.io_postgresqls.yaml
  charts/aiven-operator-crds/templates/aiven.io_projects.yaml
  charts/aiven-operator-crds/templates/aiven.io_projectvpcs.yaml
  charts/aiven-operator-crds/templates/aiven.io_redis.yaml
  charts/aiven-operator-crds/templates/aiven.io_serviceintegrations.yaml
  charts/aiven-operator-crds/templates/aiven.io_serviceusers.yaml
  docs/docs/contributing/resource-generation.md
  generators/charts/cluster_roles.go
  generators/charts/crds.go
  generators/charts/main.go
  generators/charts/utils.go
  generators/charts/version.go
  generators/charts/webhooks.go
  go.mod
  go.sum
Labels: enhancement

#310 refactor(ip_filter): remove backward compatibility
  CHANGELOG.md
  api/v1alpha1/userconfig/service/cassandra/cassandra.go
  api/v1alpha1/userconfig/service/clickhouse/clickhouse.go
  api/v1alpha1/userconfig/service/grafana/grafana.go
  api/v1alpha1/userconfig/service/kafka/kafka.go
  api/v1alpha1/userconfig/service/kafka_connect/kafka_connect.go
  api/v1alpha1/userconfig/service/mysql/mysql.go
  api/v1alpha1/userconfig/service/opensearch/opensearch.go
  api/v1alpha1/userconfig/service/pg/pg.go
  api/v1alpha1/userconfig/service/redis/redis.go
  generators/userconfigs/generator.go
  generators/userconfigs/generator_test.go
  generators/userconfigs/pg/pg.go
Labels: enhancement

#313 feat(userconfigs): update user configs
  CHANGELOG.md
  api/v1alpha1/userconfig/integration/clickhouse_kafka/clickhouse_kafka.go
  api/v1alpha1/userconfig/service/kafka/kafka.go
  api/v1alpha1/userconfig/service/mysql/mysql.go
  api/v1alpha1/userconfig/service/opensearch/opensearch.go
  api/v1alpha1/userconfig/service/pg/pg.go
  api/v1alpha1/userconfig/service/redis/redis.go
  charts/aiven-operator-crds/templates/aiven.io_kafkas.yaml
  charts/aiven-operator-crds/templates/aiven.io_mysqls.yaml
  charts/aiven-operator-crds/templates/aiven.io_opensearches.yaml
  charts/aiven-operator-crds/templates/aiven.io_postgresqls.yaml
  charts/aiven-operator-crds/templates/aiven.io_redis.yaml
  charts/aiven-operator-crds/templates/aiven.io_serviceintegrations.yaml
  config/crd/bases/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_mysqls.yaml
  config/crd/bases/aiven.io_opensearches.yaml
  config/crd/bases/aiven.io_postgresqls.yaml
  config/crd/bases/aiven.io_redis.yaml
  config/crd/bases/aiven.io_serviceintegrations.yaml
  docs/docs/api-reference/kafka.md
  docs/docs/api-reference/mysql.md
  docs/docs/api-reference/opensearch.md
  docs/docs/api-reference/postgresql.md
  docs/docs/api-reference/redis.md
  docs/docs/api-reference/serviceintegration.md
  docs/docs/contributing/resource-generation.md
  generators/docs/generator.go
  generators/docs/generator_test.go
  generators/docs/main.go
  go.mod
  go.sum
Labels: enhancement

#316 refactor(tests): test postgresql with the new suite
  .github/workflows/acceptance-tests.yaml
  Makefile
  controllers/generic_service_handler_test.go
  controllers/postgresql_controller_test.go
  tests/kafkatopic_test.go
  tests/postgresql_test.go
  tests/suite.go
Labels: enhancement

#317 refactor(tests): test grafana with the new suite
  .github/workflows/acceptance-tests.yaml
  controllers/grafana_controller_test.go
  tests/grafana_test.go
Labels: enhancement
