Repository aiven/aiven-operator, pull requests merged in 2023-06, with the labels that each got.

#422 ci(lint): remove deprecated structcheck linter
  .golangci.yml
Labels: enhancement

#423 chore: remove deprecated unclean_leader_election_enable from kafka topic config
  api/v1alpha1/kafkatopic_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/aiven-operator-crds/templates/aiven.io_kafkatopics.yaml
  config/crd/bases/aiven.io_crd-all.gen.yaml
  config/crd/bases/aiven.io_kafkatopics.yaml
  controllers/kafkatopic_controller.go
  docs/docs/api-reference/kafkatopic.md
Labels: enhancement

#432 fix(kafka): add missing sasl port
  CHANGELOG.md
  controllers/kafka_controller.go
  tests/kafka_test.go
Labels: bug

#434 chore(release): v0.12.1
  CHANGELOG.md
  charts/aiven-operator-crds/Chart.yaml
  charts/aiven-operator/Chart.yaml
  docs/docs/changelog.md
Labels: release

#435 chore(release): v0.12.2
  CHANGELOG.md
  api/v1alpha1/userconfig/integration/datadog/zz_generated.deepcopy.go
  charts/aiven-operator-crds/Chart.yaml
  charts/aiven-operator/Chart.yaml
  docs/docs/changelog.md
Labels: release

#437 fix(kafka): expose schema registry port
  CHANGELOG.md
  api/v1alpha1/kafka_types.go
  charts/aiven-operator-crds/templates/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_kafkas.yaml
  controllers/kafka_controller.go
  docs/docs/api-reference/kafka.md
  tests/kafka_test.go
Labels: bug

#442 fix(kafka): remove prometheus port expose
  CHANGELOG.md
  api/v1alpha1/kafka_types.go
  charts/aiven-operator-crds/templates/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_kafkas.yaml
  controllers/kafka_controller.go
  docs/docs/api-reference/kafka.md
  tests/kafka_test.go
Labels: bug
