Repository aiven/aiven-operator, pull requests merged in 2023-04, with the labels that each got.

#324 refactor(tests): test clickhouse with the new suite
  .github/workflows/acceptance-tests.yaml
  controllers/clickhouse_controller_test.go
  tests/clickhouse_test.go
  tests/grafana_test.go
  tests/suite.go
Labels: enhancement

#326 refactor(tests): test mysql with the new suite
  .github/workflows/acceptance-tests.yaml
  controllers/mysql_controller_test.go
  tests/mysql_test.go
Labels: enhancement

#328 refactor(tests): test redis with the new suite
  .github/workflows/acceptance-tests.yaml
  controllers/redis_controller_test.go
  tests/mysql_test.go
  tests/redis_test.go
Labels: enhancement

#330 refactor(tests): test cassandra with the new suite
  .github/workflows/acceptance-tests.yaml
  controllers/cassandra_controller_test.go
  tests/cassandra_test.go
Labels: enhancement

#331 refactor(tests): test opensearch with the new suite
  .github/workflows/acceptance-tests.yaml
  controllers/opensearch_controller_test.go
  tests/opensearch_test.go
Labels: enhancement

#333 refactor(tests): test kafka with the new suite
  .github/workflows/acceptance-tests.yaml
  controllers/kafka_controller_test.go
  tests/kafka_test.go
Labels: enhancement

#334 refactor(tests): test kafka acl with the new suite
  .github/workflows/acceptance-tests.yaml
  controllers/kafkaacl_controller_test.go
  tests/kafkaacl_test.go
  tests/kafkatopic_test.go
  tests/suite.go
Labels: enhancement

#332 feat: add rbac options to helm chart
  CHANGELOG.md
  charts/aiven-operator/templates/cluster_role.yaml
  charts/aiven-operator/templates/cluster_role_binding.yaml
  charts/aiven-operator/values.yaml
Labels: enhancement

#339 refactor(tests): test kafka-connect with the new suite
  .github/workflows/acceptance-tests.yaml
  controllers/kafkaconnect_controller_test.go
  tests/kafkaconnect_test.go
  tests/serviceintegration_test.go
Labels: enhancement

#341 docs(postgresql): add instructions for creating read-only replica
  docs/docs/resources/postgresql.md
Labels: documentation

#340 refactor(tests): test kafka-schema with the new suite
  .github/workflows/acceptance-tests.yaml
  Makefile
  controllers/database_controller_test.go
  controllers/kafka_controller_test.go
  controllers/kafkaschema_controller_test.go
  docs/docs/api-reference/database.md
  docs/docs/api-reference/examples/database.yaml
  docs/docs/api-reference/examples/kafkaschema.yaml
  docs/docs/api-reference/kafkaschema.md
  tests/database_test.go
  tests/kafkaacl_test.go
  tests/kafkaschema_test.go
  tests/kafkatopic_test.go
  tests/suite.go
Labels: enhancement

#344 refactor(tests): test kafka project vpc ref with the new suite
  .github/workflows/acceptance-tests.yaml
  CHANGELOG.md
  controllers/kafka_controller_with_projectvpc_ref_test.go
  controllers/projectvpc_controller.go
  controllers/projectvpc_controller_test.go
  docs/docs/api-reference/examples/projectvpc.yaml
  docs/docs/api-reference/projectvpc.md
  tests/kafka_with_projectvpc_ref_test.go
  tests/projectvpc_test.go
Labels: enhancement

#338 feat(charts): add rbac options to cluster_role.yaml generator
  CHANGELOG.md
  generators/charts/cluster_roles.go
Labels: enhancement

#336 fix(charts): add required RBAC permissions to update finalizers
  .github/dependabot.yml
  CHANGELOG.md
  charts/aiven-operator/templates/cluster_role.yaml
  charts/aiven-operator/templates/cluster_role_binding.yaml
  config/rbac/role.yaml
  config/samples/aiven.io_v1alpha1_kafka.yaml
  controllers/clickhouseuser_controller.go
  controllers/connectionpool_controller.go
  controllers/kafka_controller.go
  controllers/kafkaconnect_controller.go
  controllers/kafkaconnector_controller.go
  controllers/opensearch_controller.go
  controllers/postgresql_controller.go
  controllers/project_controller.go
  controllers/redis_controller.go
  controllers/serviceuser_controller.go
  docs/docs/api-reference/examples/kafka.yaml
  docs/docs/api-reference/kafka.md
  generators/charts/cluster_roles.go
  test/e2e/kafka-topic/simple-kafka-topic/01-kafka.yaml
  test/e2e/kafka/kafka-simple-cluster/01-kafka.yaml
Labels: bug

#352 refactor(clickhouseuser): replace old controller with handler
  .github/workflows/acceptance-tests.yaml
  CHANGELOG.md
  api/v1alpha1/clickhouseuser_types.go
  charts/aiven-operator-crds/templates/aiven.io_clickhouseusers.yaml
  config/crd/bases/aiven.io_clickhouseusers.yaml
  controllers/clickhouse_controller_test.go
  controllers/clickhouseuser_controller.go
  controllers/clickhouseuser_controller_test.go
  docs/docs/api-reference/clickhouse.md
  docs/docs/api-reference/clickhouseuser.md
  docs/docs/api-reference/examples/clickhouse.yaml
  docs/docs/api-reference/examples/clickhouseuser.yaml
  tests/clickhouseuser_test.go
Labels: enhancement

#362 feat(client): add version build flag to the client user-agent
  .github/workflows/release.yaml
  Dockerfile
  controllers/basic_controller.go
  controllers/common.go
  controllers/suite_test.go
  tests/suite_test.go
Labels: enhancement

#363 chore(release): v0.10.0
  CHANGELOG.md
  charts/aiven-operator-crds/Chart.yaml
  charts/aiven-operator/Chart.yaml
  docs/docs/changelog.md
Labels: release

#365 fix(docs): examples ends wo empty line
  docs/docs/api-reference/examples/kafkaschema.yaml
  docs/docs/api-reference/kafkaschema.md
  generators/docs/generator.go
Labels: bug, documentation

#368 ci: fix github actions yaml spec errors
  .github/dependabot.yml
  .github/workflows/generate.yaml
  .github/workflows/lint.yaml
  .github/workflows/pages.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  .golangci.yml
Labels: enhancement

#361 test(charts): install in kind
  Makefile
  docs/docs/contributing/developer-guide.md
  test/e2e/kuttl-test.preinstalled.yaml
Labels: enhancement

#371 fix(service_integration): improve webhooks checks
  CHANGELOG.md
  api/v1alpha1/serviceintegration_types.go
  api/v1alpha1/serviceintegration_webhook.go
  api/v1alpha1/setup_webhooks.go
  api/v1alpha1/webhook_suite_test.go
  charts/aiven-operator-crds/templates/aiven.io_serviceintegrations.yaml
  config/crd/bases/aiven.io_serviceintegrations.yaml
  controllers/common.go
  controllers/generic_service_handler.go
  controllers/serviceintegration_controller.go
  docs/docs/api-reference/serviceintegration.md
  go.mod
  main.go
  tests/serviceintegration_test.go
  tests/suite.go
  tests/suite_test.go
Labels: bug, enhancement

#370 feat(chart): allow to disable helm capabilities check
  charts/aiven-operator/Chart.yaml
  charts/aiven-operator/templates/ensure_cert_manager_if_webhooks_are_enabled.yaml
  charts/aiven-operator/values.yaml
Labels: enhancement

#377 ci(release): add charts sync job
  .github/sync.yml
  .github/workflows/release.yaml
Labels: enhancement

#382 chore(release): v0.11.0
  CHANGELOG.md
  charts/aiven-operator-crds/Chart.yaml
  charts/aiven-operator/Chart.yaml
  docs/docs/changelog.md
Labels: release
