Repository aiven/aiven-operator, pull requests merged in 2023-02, with the labels that each got.

#252 Remove empty testing section
  docs/content/en/docs/resources/opensearch/_index.md
Labels: documentation

#244 upgrade Kafka kind
  .golangci.yml
  CHANGELOG.md
  Makefile
  api/v1alpha1/kafka_types.go
  api/v1alpha1/userconfigs/cassandra/cassandra.go
  api/v1alpha1/userconfigs/grafana/grafana.go
  api/v1alpha1/userconfigs/kafka/kafka.go
  api/v1alpha1/userconfigs/kafka/zz_generated.deepcopy.go
  api/v1alpha1/userconfigs/mysql/mysql.go
  api/v1alpha1/userconfigs/mysql/zz_generated.deepcopy.go
  api/v1alpha1/userconfigs/pg/pg.go
  api/v1alpha1/userconfigs/pg/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_mysqls.yaml
  config/crd/bases/aiven.io_postgresqls.yaml
  controllers/cassandra_controller.go
  controllers/controller.go
  controllers/generic_service_handler.go
  controllers/grafana_controller.go
  controllers/kafka_controller.go
  controllers/kafka_controller_test.go
  controllers/mysql_controller.go
  controllers/postgresql_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  userconfigs_generator/generator.go
  userconfigs_generator/generator_test.go
  userconfigs_generator/pg/pg.go
Labels: enhancement

#253 add service integrations
  .github/workflows/acceptance-tests.yaml
  CHANGELOG.md
  api/v1alpha1/common.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/aiven.io_cassandras.yaml
  config/crd/bases/aiven.io_clickhouses.yaml
  config/crd/bases/aiven.io_grafanas.yaml
  config/crd/bases/aiven.io_kafkaconnects.yaml
  config/crd/bases/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_mysqls.yaml
  config/crd/bases/aiven.io_opensearches.yaml
  config/crd/bases/aiven.io_postgresqls.yaml
  config/crd/bases/aiven.io_redis.yaml
  controllers/generic_service_handler.go
  controllers/generic_service_handler_test.go
Labels: enhancement, customer request

#254 add KafkaTopic min_cleanable_dirty_ratio config field support
  .github/workflows/acceptance-tests.yaml
  CHANGELOG.md
  Makefile
  api/v1alpha1/kafkatopic_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/aiven.io_kafkatopics.yaml
  controllers/basic_controller.go
  controllers/basic_controller_test.go
  controllers/kafkatopic_controller_test.go
Labels: enhancement

#256 upgrade clickhouse kind
  CHANGELOG.md
  api/v1alpha1/clickhouse_types.go
  api/v1alpha1/userconfigs/clickhouse/clickhouse.go
  api/v1alpha1/userconfigs/clickhouse/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/aiven.io_clickhouses.yaml
  controllers/clickhouse_controller.go
  controllers/clickhouse_controller_test.go
  main.go
Labels: enhancement

#255 upgrade redis kind user config and controller
  CHANGELOG.md
  api/v1alpha1/clickhouse_types.go
  api/v1alpha1/redis_types.go
  api/v1alpha1/userconfigs/clickhouse/clickhouse.go
  api/v1alpha1/userconfigs/clickhouse/zz_generated.deepcopy.go
  api/v1alpha1/userconfigs/redis/redis.go
  api/v1alpha1/userconfigs/redis/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/aiven.io_clickhouses.yaml
  config/crd/bases/aiven.io_redis.yaml
  controllers/clickhouse_controller.go
  controllers/clickhouse_controller_test.go
  controllers/redis_controller.go
  controllers/redis_controller_test.go
  main.go
  userconfigs_generator/pg/zz_generated.deepcopy.go
Labels: enhancement

#259 upgrade kafka connect
  CHANGELOG.md
  api/v1alpha1/common.go
  api/v1alpha1/kafkaconnect_types.go
  api/v1alpha1/userconfigs/kafka_connect/kafka_connect.go
  api/v1alpha1/userconfigs/kafka_connect/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/aiven.io_kafkaconnects.yaml
  controllers/kafkaconnect_controller.go
  controllers/kafkaconnect_controller_test.go
  main.go
Labels: enhancement

#257 upgrade opensearch kind user config and controller
  CHANGELOG.md
  api/v1alpha1/common.go
  api/v1alpha1/kafkaconnect_types.go
  api/v1alpha1/opensearch_types.go
  api/v1alpha1/userconfigs/kafka_connect/kafka_connect.go
  api/v1alpha1/userconfigs/kafka_connect/zz_generated.deepcopy.go
  api/v1alpha1/userconfigs/opensearch/opensearch.go
  api/v1alpha1/userconfigs/opensearch/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/aiven.io_kafkaconnects.yaml
  config/crd/bases/aiven.io_opensearches.yaml
  controllers/kafkaconnect_controller.go
  controllers/kafkaconnect_controller_test.go
  controllers/opensearch_controller.go
  controllers/opensearch_controller_test.go
  main.go
Labels: enhancement

#260 remove field name from comment
  api/v1alpha1/userconfigs/cassandra/cassandra.go
  api/v1alpha1/userconfigs/clickhouse/clickhouse.go
  api/v1alpha1/userconfigs/grafana/grafana.go
  api/v1alpha1/userconfigs/kafka/kafka.go
  api/v1alpha1/userconfigs/kafka_connect/kafka_connect.go
  api/v1alpha1/userconfigs/mysql/mysql.go
  api/v1alpha1/userconfigs/opensearch/opensearch.go
  api/v1alpha1/userconfigs/pg/pg.go
  api/v1alpha1/userconfigs/redis/redis.go
  config/crd/bases/aiven.io_cassandras.yaml
  config/crd/bases/aiven.io_clickhouses.yaml
  config/crd/bases/aiven.io_grafanas.yaml
  config/crd/bases/aiven.io_kafkaconnects.yaml
  config/crd/bases/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_mysqls.yaml
  config/crd/bases/aiven.io_opensearches.yaml
  config/crd/bases/aiven.io_postgresqls.yaml
  config/crd/bases/aiven.io_redis.yaml
  userconfigs_generator/generator.go
  userconfigs_generator/pg/pg.go
Labels: enhancement

#265 Building arm64 image
  .github/workflows/release.yaml
  Dockerfile
Labels: enhancement

#263 build(deps): use retryable http client
  CHANGELOG.md
  api/v1alpha1/userconfigs/cassandra/cassandra.go
  api/v1alpha1/userconfigs/kafka/kafka.go
  api/v1alpha1/userconfigs/pg/pg.go
  config/crd/bases/aiven.io_cassandras.yaml
  config/crd/bases/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_postgresqls.yaml
  go.mod
  go.sum
Labels: dependencies, go

#266 feat: docs generator
  Makefile
  api/v1alpha1/common.go
  config/crd/bases/aiven.io_cassandras.yaml
  config/crd/bases/aiven.io_clickhouses.yaml
  config/crd/bases/aiven.io_grafanas.yaml
  config/crd/bases/aiven.io_kafkaconnects.yaml
  config/crd/bases/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_mysqls.yaml
  config/crd/bases/aiven.io_opensearches.yaml
  config/crd/bases/aiven.io_postgresqls.yaml
  config/crd/bases/aiven.io_redis.yaml
  docs/docs/CHANGELOG.md
  docs/docs/api-reference.md
  docs/docs/api-reference/cassandra.md
  docs/docs/api-reference/clickhouse.md
  docs/docs/api-reference/clickhouseuser.md
  docs/docs/api-reference/connectionpool.md
  docs/docs/api-reference/database.md
  docs/docs/api-reference/grafana.md
  docs/docs/api-reference/kafka.md
  docs/docs/api-reference/kafkaacl.md
  docs/docs/api-reference/kafkaconnect.md
  docs/docs/api-reference/kafkaconnector.md
  docs/docs/api-reference/kafkaschema.md
  docs/docs/api-reference/kafkatopic.md
  docs/docs/api-reference/mysql.md
  docs/docs/api-reference/opensearch.md
  docs/docs/api-reference/postgresql.md
  docs/docs/api-reference/project.md
  docs/docs/api-reference/projectvpc.md
  docs/docs/api-reference/redis.md
  docs/docs/api-reference/serviceintegration.md
  docs/docs/api-reference/serviceuser.md
  docs/mkdocs.yml
  docs_generator/main.go
  hack/genrefs/config.json
  hack/genrefs/main.go
  hack/genrefs/template/pkg.tpl
  hack/genrefs/template/template.tpl
Labels: enhancement

#268 release: v0.8.0
  CHANGELOG.md
  docs/docs/api-reference/index.md
  docs/docs/changelog.md
  docs/docs/contributing/developer-guide.md
  docs/docs/contributing/index.md
  docs/mkdocs.yml
Labels: release

#246 Add Cassandra section to docs
  docs/docs/resources/cassandra.md
  docs/mkdocs.yml
Labels: documentation

#270 docs(gen): disable emoji
  docs/mkdocs.yml
Labels: documentation

#275 Split console inputs and output examples in docs
  docs/docs/installation/helm.md
  docs/docs/resources/kafka/connect.md
  docs/docs/resources/kafka/index.md
  docs/docs/resources/kafka/schema.md
  docs/docs/resources/opensearch.md
  docs/docs/resources/postgresql.md
  docs/docs/resources/project-vpc.md
  docs/docs/resources/project.md
  docs/docs/resources/redis.md
  docs/docs/resources/service-integrations.md
  docs/docs/troubleshooting.md
Labels: documentation

#274 docs: add examples
  Makefile
  api/v1alpha1/common.go
  api/v1alpha1/kafkaconnect_types.go
  config/crd/bases/aiven.io_cassandras.yaml
  config/crd/bases/aiven.io_clickhouses.yaml
  config/crd/bases/aiven.io_clickhouseusers.yaml
  config/crd/bases/aiven.io_connectionpools.yaml
  config/crd/bases/aiven.io_grafanas.yaml
  config/crd/bases/aiven.io_kafkaconnects.yaml
  config/crd/bases/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_mysqls.yaml
  config/crd/bases/aiven.io_opensearches.yaml
  config/crd/bases/aiven.io_postgresqls.yaml
  config/crd/bases/aiven.io_projects.yaml
  config/crd/bases/aiven.io_redis.yaml
  config/crd/bases/aiven.io_serviceusers.yaml
  docs/docs/api-reference/cassandra.md
  docs/docs/api-reference/clickhouse.md
  docs/docs/api-reference/clickhouseuser.md
  docs/docs/api-reference/connectionpool.md
  docs/docs/api-reference/database.md
  docs/docs/api-reference/examples/cassandra.yaml
  docs/docs/api-reference/examples/clickhouse.yaml
  docs/docs/api-reference/examples/grafana.yaml
  docs/docs/api-reference/examples/kafka.yaml
  docs/docs/api-reference/examples/kafkatopic.yaml
  docs/docs/api-reference/examples/mysql.yaml
  docs/docs/api-reference/examples/opensearch.yaml
  docs/docs/api-reference/examples/postgresql.yaml
  docs/docs/api-reference/examples/redis.yaml
  docs/docs/api-reference/grafana.md
  docs/docs/api-reference/kafka.md
  docs/docs/api-reference/kafkaacl.md
  docs/docs/api-reference/kafkaconnect.md
  docs/docs/api-reference/kafkaconnector.md
  docs/docs/api-reference/kafkaschema.md
  docs/docs/api-reference/kafkatopic.md
  docs/docs/api-reference/mysql.md
  docs/docs/api-reference/opensearch.md
  docs/docs/api-reference/postgresql.md
  docs/docs/api-reference/project.md
  docs/docs/api-reference/projectvpc.md
  docs/docs/api-reference/redis.md
  docs/docs/api-reference/serviceintegration.md
  docs/docs/api-reference/serviceuser.md
  docs/docs/changelog.md
  docs_generator/main.go
  docs_generator/validator.go
  go.mod
  go.sum
Labels: documentation

#277 add serviceIntegration property doc
  api/v1alpha1/common.go
  config/crd/bases/aiven.io_cassandras.yaml
  config/crd/bases/aiven.io_clickhouses.yaml
  config/crd/bases/aiven.io_grafanas.yaml
  config/crd/bases/aiven.io_kafkaconnects.yaml
  config/crd/bases/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_mysqls.yaml
  config/crd/bases/aiven.io_opensearches.yaml
  config/crd/bases/aiven.io_postgresqls.yaml
  config/crd/bases/aiven.io_redis.yaml
  docs/docs/api-reference/cassandra.md
  docs/docs/api-reference/clickhouse.md
  docs/docs/api-reference/grafana.md
  docs/docs/api-reference/kafka.md
  docs/docs/api-reference/kafkaconnect.md
  docs/docs/api-reference/mysql.md
  docs/docs/api-reference/opensearch.md
  docs/docs/api-reference/postgresql.md
  docs/docs/api-reference/redis.md
Labels: documentation
