Repository aiven/aiven-operator, pull requests merged in 2023-12, with the labels that each got.

#558 chore(release): v0.16.0
  CHANGELOG.md
  charts/aiven-operator-crds/Chart.yaml
  charts/aiven-operator/Chart.yaml
  docs/docs/changelog.md
Labels: release

#559 refactor(vpc): prevent vpc deletion with running services
  CHANGELOG.md
  controllers/projectvpc_controller.go
Labels: enhancement

#563 feat(kafka): expose schema registry and rest uris
  CHANGELOG.md
  controllers/kafka_controller.go
  tests/kafka_test.go
Labels: enhancement

#561 feat(connection_pool): expose pool name
  CHANGELOG.md
  api/v1alpha1/connectionpool_types.go
  charts/aiven-operator-crds/templates/aiven.io_connectionpools.yaml
  config/crd/bases/aiven.io_connectionpools.yaml
  controllers/connectionpool_controller.go
  docs/docs/api-reference/connectionpool.md
  tests/connectionpool_test.go
Labels: enhancement

#565 fix(serviceuser): expose different port when sasl enabled
  CHANGELOG.md
  Makefile
  controllers/serviceuser_controller.go
  tests/serviceuser_test.go
Labels: bug

#570 chore(release): v0.16.1
  CHANGELOG.md
  charts/aiven-operator-crds/Chart.yaml
  charts/aiven-operator/Chart.yaml
  docs/docs/changelog.md
Labels: release

#572 fix(makefile): install `goimports` to $(LOCALBIN)
  Makefile
Labels: bug

#568 chore(serviceuser): add pg test
  tests/serviceuser_test.go
Labels: enhancement
