Repository aiven/aiven-operator, pull requests merged in 2023-01, with the labels that each got.

#218 remove "never" from dow choices
  CHANGELOG.md
  api/v1alpha1/common.go
  config/crd/bases/aiven.io_clickhouses.yaml
  config/crd/bases/aiven.io_kafkaconnects.yaml
  config/crd/bases/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_opensearches.yaml
  config/crd/bases/aiven.io_postgresqls.yaml
  config/crd/bases/aiven.io_redis.yaml
Labels: enhancement

#220 fix aiven client useragent
  controllers/common.go
Labels: bug

#221 add development flag to main.go
  CHANGELOG.md
  main.go
Labels: enhancement

#219 add userconfig generator, add MySQL kind, add genericServiceHandler
  CHANGELOG.md
  Makefile
  PROJECT
  api/v1alpha1/mysql_types.go
  api/v1alpha1/mysql_webhook.go
  api/v1alpha1/userconfigs/mysql/mysql.go
  api/v1alpha1/userconfigs/mysql/zz_generated.deepcopy.go
  api/v1alpha1/webhook_suite_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/aiven.io_mysqls.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_mysqls.yaml
  config/crd/patches/webhook_in_mysqls.yaml
  config/rbac/mysql_editor_role.yaml
  config/rbac/mysql_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/_v1alpha1_mysql.yaml
  config/samples/kustomization.yaml
  config/webhook/manifests.yaml
  controllers/clickhouse_controller_test.go
  controllers/controller.go
  controllers/generic_service_handler.go
  controllers/mysql_controller.go
  controllers/mysql_controller_test.go
  controllers/projectvpc_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/genrefs/main.go
  main.go
  test/e2e/clickhouse/clickhouse-simple-cluster/01-clickhouse.yaml
  test/e2e/kuttl-test.yaml
  test/e2e/mysql/mysql-simple-cluster/00-secret.yaml
  test/e2e/mysql/mysql-simple-cluster/01-mysql.yaml
  test/e2e/mysql/mysql-simple-cluster/02-check.yaml
  test/e2e/mysql/mysql-simple-cluster/03-delete.yaml
  userconfigs_generator/generator.go
  userconfigs_generator/generator_test.go
  userconfigs_generator/generator_test_expected.go
  userconfigs_generator/generator_test_source.yml
  userconfigs_generator/main.go
Labels: enhancement

#222 let run acc tests on demand
  .github/workflows/acceptance-tests.yaml
Labels: enhancement

#223 fix run acc tests on demand
  .github/workflows/acceptance-tests.yaml
Labels: bug

#224 release: v0.6.0
  CHANGELOG.md
Labels: release

#225 add Cassandra kind
  CHANGELOG.md
  PROJECT
  api/v1alpha1/cassandra_types.go
  api/v1alpha1/cassandra_webhook.go
  api/v1alpha1/userconfigs/cassandra/cassandra.go
  api/v1alpha1/userconfigs/cassandra/zz_generated.deepcopy.go
  api/v1alpha1/webhook_suite_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/aiven.io_cassandras.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_cassandras.yaml
  config/crd/patches/webhook_in_cassandras.yaml
  config/rbac/cassandra_editor_role.yaml
  config/rbac/cassandra_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/_v1alpha1_cassandra.yaml
  config/samples/kustomization.yaml
  config/webhook/manifests.yaml
  controllers/cassandra_controller.go
  controllers/cassandra_controller_test.go
  controllers/generic_service_handler.go
  controllers/mysql_controller.go
  controllers/suite_test.go
  main.go
  test/e2e/cassandra/cassandra-simple-cluster/00-secret.yaml
  test/e2e/cassandra/cassandra-simple-cluster/01-cassandra.yaml
  test/e2e/cassandra/cassandra-simple-cluster/02-check.yaml
  test/e2e/cassandra/cassandra-simple-cluster/03-delete.yaml
  test/e2e/kuttl-test.yaml
Labels: enhancement

#228 fix kafka acl lifecycle
  CHANGELOG.md
  controllers/kafkaacl_controller.go
  controllers/kafkaacl_controller_test.go
Labels: bug

#230 run acc for go file change only
  .github/workflows/acceptance-tests-ignore.yaml
  .github/workflows/acceptance-tests.yaml
Labels: enhancement

#234 release: v0.7.0
  CHANGELOG.md
Labels: release

#235 ci(test): drop required acctests
  .github/workflows/acceptance-tests-ignore.yaml
  .github/workflows/acceptance-tests.yaml
Labels: enhancement

#236 fix MySQL webhook name
  CHANGELOG.md
  api/v1alpha1/mysql_webhook.go
  config/webhook/manifests.yaml
Labels: bug

#237 fix cassandra and grafana webhooks
  api/v1alpha1/cassandra_webhook.go
  api/v1alpha1/grafana_webhook.go
  config/webhook/manifests.yaml
Labels: bug

#238 fix webhooks endpoints
  api/v1alpha1/cassandra_webhook.go
  api/v1alpha1/grafana_webhook.go
  config/webhook/manifests.yaml
Labels: bug

#232 fix enum generation
  userconfigs_generator/generator.go
  userconfigs_generator/generator_test.go
  userconfigs_generator/generator_test_expected.go
Labels: bug

#229 Add OpenSearch resource to docs
  config/samples/aiven.io_v1alpha1_clickhouse.yaml
  config/samples/aiven.io_v1alpha1_opensearch.yaml
  docs/content/en/docs/resources/opensearch/_index.md
  test/e2e/opensearch/opensearch-simple-cluster/01-opensearch.yaml
  test/e2e/projectvpc/projectvpc-ref/01-resources.yaml
Labels: documentation

#227 Add Redis resource to docs
  docs/content/en/docs/resources/redis/_index.md
Labels: documentation

#240 release: v0.7.1
  CHANGELOG.md
Labels: release

#242 ci(tests): separate job per each package
  .github/workflows/acceptance-tests.yaml
  Makefile
Labels: enhancement

#243 upgrade PostgreSQL kind, make cloud_name mutable
  CHANGELOG.md
  Makefile
  api/v1alpha1/common.go
  api/v1alpha1/postgresql_types.go
  api/v1alpha1/userconfigs/pg/pg.go
  api/v1alpha1/userconfigs/pg/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/aiven.io_cassandras.yaml
  config/crd/bases/aiven.io_clickhouses.yaml
  config/crd/bases/aiven.io_grafanas.yaml
  config/crd/bases/aiven.io_kafkaconnects.yaml
  config/crd/bases/aiven.io_kafkas.yaml
  config/crd/bases/aiven.io_mysqls.yaml
  config/crd/bases/aiven.io_opensearches.yaml
  config/crd/bases/aiven.io_postgresqls.yaml
  config/crd/bases/aiven.io_redis.yaml
  controllers/cassandra_controller.go
  controllers/controller_test.go
  controllers/generic_service_handler.go
  controllers/grafana_controller.go
  controllers/mysql_controller.go
  controllers/postgresql_controller.go
  controllers/postgresql_controller_test.go
  main.go
Labels: enhancement

#248 fix: unable to remove resources with invalid token
  controllers/controller.go
Labels: bug
