Repository aiven/aiven-operator, pull requests merged in 2024-04, with the labels that each got.

#696 chore: fix release flow
  .github/workflows/release.yml
  Dockerfile
  main.go
Labels: bug

#698 chore(release): v0.18.1
  CHANGELOG.md
  charts/aiven-operator-crds/Chart.yaml
  charts/aiven-operator/Chart.yaml
  docs/docs/changelog.md
Labels: release

#697 docs: add missing resources
  docs/docs/api-reference/examples/kafkaschemaregistryacl.yaml
  docs/docs/api-reference/kafkaschemaregistryacl.md
  docs/mkdocs.yml
Labels: documentation

#687 ci(dependabot): run on weekly basis
  .github/dependabot.yml
Labels: enhancement

#700 docs(changelog): add missing user-agent entry
  CHANGELOG.md
  docs/docs/changelog.md
Labels: documentation

#702 Revert "build(deps): bump wagoid/commitlint-github-action from 5 to 6"
  .github/dependabot.yml
  .github/workflows/lint.yml
  commitlint.config.js
Labels: bug

#701 fix(docs): indentation formatting on several admonitions
  docs/docs/installation/helm.md
  docs/docs/installation/prerequisites.md
  docs/docs/resources/cassandra.md
  docs/docs/resources/kafka/index.md
  docs/docs/resources/opensearch.md
  docs/docs/resources/postgresql.md
  docs/docs/resources/project-vpc.md
  docs/docs/resources/project.md
  docs/docs/resources/redis.md
  docs/docs/resources/service-integrations.md
Labels: documentation

#704 test: uniform user-agent
  tests/suite_test.go
Labels: enhancement

#705 chore: unified user-agent format
  CHANGELOG.md
  controllers/common.go
Labels: enhancement

#710 fix: service account roles
  CHANGELOG.md
  api/v1alpha1/clickhouserole_types.go
  api/v1alpha1/database_types.go
  api/v1alpha1/kafkaschemaregistryacl_types.go
  charts/aiven-operator-crds/templates/aiven.io_clickhouseroles.yaml
  charts/aiven-operator-crds/templates/aiven.io_databases.yaml
  charts/aiven-operator-crds/templates/aiven.io_kafkaschemaregistryacls.yaml
  charts/aiven-operator/templates/cluster_role.yaml
  config/crd/bases/aiven.io_clickhouseroles.yaml
  config/crd/bases/aiven.io_databases.yaml
  config/crd/bases/aiven.io_kafkaschemaregistryacls.yaml
  config/rbac/role.yaml
  controllers/cassandra_controller.go
  controllers/clickhouse_controller.go
  controllers/clickhousedatabase_controller.go
  controllers/clickhouserole_controller.go
  controllers/clickhouseuser_controller.go
  controllers/connectionpool_controller.go
  controllers/database_controller.go
  controllers/grafana_controller.go
  controllers/kafka_controller.go
  controllers/kafkaacl_controller.go
  controllers/kafkaconnect_controller.go
  controllers/kafkaconnector_controller.go
  controllers/kafkaschema_controller.go
  controllers/kafkaschemaregistryacl_controller.go
  controllers/kafkatopic_controller.go
  controllers/mysql_controller.go
  controllers/opensearch_controller.go
  controllers/postgresql_controller.go
  controllers/project_controller.go
  controllers/projectvpc_controller.go
  controllers/redis_controller.go
  controllers/serviceintegration_controller.go
  controllers/serviceuser_controller.go
Labels: bug

#714 chore: update chart repo PAT secret name
  .github/workflows/force-sync-charts.yml
  .github/workflows/release.yml
Labels: enhancement
