Repository aiven/aiven-operator, pull requests merged in 2024-06, with the labels that each got.

#746 fix(ci): add `token` to kustomize-github-action
  .github/workflows/lint.yml
  .github/workflows/release.yml
Labels: github_actions

#745 chore(release): v0.20.0
  CHANGELOG.md
  charts/aiven-operator-crds/Chart.yaml
  charts/aiven-operator/Chart.yaml
  docs/docs/changelog.md
Labels: release

#748 docs: reorder latest changelog entries
  CHANGELOG.md
Labels: documentation, enhancement

#771 docs(clickhouse): add example
  docs/docs/resources/clickhouse.md
  docs/mkdocs.yml
Labels: documentation
