Repository aiven/aiven-operator, pull requests merged in 2024-02, with the labels that each got.

#614 ci: add options to pass commitlint to trunk-upgrade action
  .github/workflows/trunk-upgrade.yml
Labels: github_actions

#622 ci(codeql): add setup Go step
  .github/workflows/lint.yml
Labels: enhancement

#624 Update developer docs
  Makefile
  docs/docs/.snippets/pg-example.yaml
  docs/docs/assets/developer-guide-k9s.jpg
  docs/docs/authentication.md
  docs/docs/contributing/developer-guide.md
  docs/docs/contributing/index.md
  docs/docs/index.md
  docs/docs/installation/helm.md
  docs/docs/installation/uninstalling.md
  docs/docs/resources/cassandra.md
  docs/docs/resources/kafka/connect.md
  docs/docs/resources/kafka/index.md
  docs/docs/resources/kafka/schema.md
  docs/docs/resources/mysql.md
  docs/docs/resources/opensearch.md
  docs/docs/resources/postgresql.md
  docs/docs/resources/project-vpc.md
  docs/docs/resources/project.md
  docs/docs/resources/redis.md
  docs/docs/resources/service-integrations.md
  docs/mkdocs.yml
Labels: documentation, enhancement

#629 feat: use generated client in service integrations controller
  controllers/basic_controller.go
  controllers/clickhouseuser_controller.go
  controllers/common.go
  controllers/connectionpool_controller.go
  controllers/database_controller.go
  controllers/generic_service_handler.go
  controllers/kafkaacl_controller.go
  controllers/kafkaconnector_controller.go
  controllers/kafkaschema_controller.go
  controllers/kafkatopic_controller.go
  controllers/project_controller.go
  controllers/projectvpc_controller.go
  controllers/serviceintegration_controller.go
  controllers/serviceuser_controller.go
  go.mod
  go.sum
Labels: enhancement

#632 chore: upgrade to go 1.22
  .trunk/trunk.yaml
  Dockerfile
  go.mod
  go.sum
Labels: enhancement

#635 fix(tests): move defaultNamespace const to fix undefined variable issue
  tests/session.go
  tests/suite_test.go
Labels: bug

#626 feat: update KafkaTopicConfig
  CHANGELOG.md
  api/v1alpha1/kafkatopic_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/aiven-operator-crds/templates/aiven.io_kafkatopics.yaml
  config/crd/bases/aiven.io_kafkatopics.yaml
  controllers/kafkatopic_controller.go
  docs/docs/api-reference/kafkatopic.md
  tests/kafkatopic_test.go
Labels: enhancement

#643 ci(trunk): fix docs linting
  .trunk/trunk.yaml
  controllers/common.go
  docs/docs/api-reference/grafana.md
  docs/docs/api-reference/kafka.md
  docs/docs/api-reference/kafkaconnect.md
  docs/docs/api-reference/kafkatopic.md
  docs/docs/api-reference/mysql.md
  docs/docs/api-reference/opensearch.md
  docs/docs/api-reference/postgresql.md
  docs/docs/api-reference/redis.md
  docs/docs/api-reference/serviceintegration.md
  generators/docs/generator.go
Labels: bug

#638 ci(tests): concurrency support
  .github/workflows/tests.yml
  Makefile
Labels: enhancement, github_actions

#636 feat(tests): log operation status when calling `retryForever`
  tests/projectvpc_test.go
  tests/session.go
Labels: enhancement

#654 refactor(tests): use envconfig for configuration
  go.mod
  tests/cassandra_test.go
  tests/clickhouse_test.go
  tests/clickhouseuser_test.go
  tests/connectionpool_test.go
  tests/database_test.go
  tests/generic_service_handler_test.go
  tests/grafana_test.go
  tests/kafka_test.go
  tests/kafka_with_projectvpc_ref_test.go
  tests/kafkaacl_test.go
  tests/kafkaconnect_test.go
  tests/kafkaschema_test.go
  tests/kafkatopic_test.go
  tests/mysql_test.go
  tests/opensearch_test.go
  tests/postgresql_test.go
  tests/project_test.go
  tests/projectvpc_test.go
  tests/redis_test.go
  tests/service_opts_test.go
  tests/serviceintegration_test.go
  tests/serviceuser_test.go
  tests/session.go
  tests/suite_test.go
Labels: enhancement

#645 feat: check PG upgrade task before attempting to upgrade service
  CHANGELOG.md
  controllers/cassandra_controller.go
  controllers/clickhouse_controller.go
  controllers/generic_service_handler.go
  controllers/grafana_controller.go
  controllers/kafka_controller.go
  controllers/kafkaconnect_controller.go
  controllers/mysql_controller.go
  controllers/opensearch_controller.go
  controllers/postgresql_controller.go
  controllers/redis_controller.go
  tests/postgresql_test.go
Labels: enhancement

#658 ci(tests): add sweeper to destroy resources after test runs
  .github/workflows/tests.yml
  Makefile
  sweeper/main.go
  sweeper/service_integrations.go
  sweeper/services.go
  sweeper/vpcs.go
Labels: enhancement

#657 ci(tests): fix tests panic
  .github/workflows/tests.yml
  Makefile
  tests/cassandra_test.go
  tests/clickhouse_test.go
  tests/clickhouseuser_test.go
  tests/connectionpool_test.go
  tests/database_test.go
  tests/generic_service_handler_test.go
  tests/grafana_test.go
  tests/kafka_test.go
  tests/kafka_with_projectvpc_ref_test.go
  tests/kafkaacl_test.go
  tests/kafkaconnect_test.go
  tests/kafkaschema_test.go
  tests/kafkatopic_test.go
  tests/mysql_test.go
  tests/opensearch_test.go
  tests/postgresql_test.go
  tests/project_test.go
  tests/projectvpc_test.go
  tests/redis_test.go
  tests/service_opts_test.go
  tests/serviceintegration_test.go
  tests/serviceuser_test.go
  tests/session.go
  tests/suite_test.go
Labels: enhancement
