Repository aiven/aiven-operator, pull requests merged in 2024-07, with the labels that each got.

#772 docs: format headings and placeholders
  README.md
  docs/docs/authentication.md
  docs/docs/contributing/developer-guide.md
  docs/docs/installation/helm.md
  docs/docs/installation/kubectl.md
  docs/docs/installation/uninstalling.md
  docs/docs/resources/cassandra.md
  docs/docs/resources/kafka/connect.md
  docs/docs/resources/kafka/index.md
  docs/docs/resources/kafka/schema.md
  docs/docs/resources/mysql.md
  docs/docs/resources/opensearch.md
  docs/docs/resources/postgresql.md
  docs/docs/resources/project-vpc.md
  docs/docs/resources/project.md
  docs/docs/resources/redis.md
  docs/docs/resources/service-integrations.md
  docs/docs/troubleshooting.md
Labels: documentation

#779 docs: add secret dependency warning
  docs/docs/api-reference/cassandra.md
  docs/docs/api-reference/clickhouse.md
  docs/docs/api-reference/clickhousedatabase.md
  docs/docs/api-reference/clickhousegrant.md
  docs/docs/api-reference/clickhouserole.md
  docs/docs/api-reference/clickhouseuser.md
  docs/docs/api-reference/connectionpool.md
  docs/docs/api-reference/database.md
  docs/docs/api-reference/grafana.md
  docs/docs/api-reference/kafka.md
  docs/docs/api-reference/kafkaacl.md
  docs/docs/api-reference/kafkaconnect.md
  docs/docs/api-reference/kafkaschema.md
  docs/docs/api-reference/kafkaschemaregistryacl.md
  docs/docs/api-reference/kafkatopic.md
  docs/docs/api-reference/mysql.md
  docs/docs/api-reference/opensearch.md
  docs/docs/api-reference/postgresql.md
  docs/docs/api-reference/project.md
  docs/docs/api-reference/projectvpc.md
  docs/docs/api-reference/redis.md
  docs/docs/api-reference/serviceintegration.md
  docs/docs/api-reference/serviceintegrationendpoint.md
  docs/docs/api-reference/serviceuser.md
  docs/docs/authentication.md
  generators/docs/generator.go
Labels: documentation

#788 chore(release): v0.23.0
  CHANGELOG.md
  charts/aiven-operator-crds/Chart.yaml
  charts/aiven-operator/Chart.yaml
  docs/docs/changelog.md
  tests/clickhousegrant_test.go
Labels: release

#791 fix(postgresql): no valid backups for read replica
  .github/workflows/tests.yml
  CHANGELOG.md
  controllers/generic_service_handler.go
  tests/kafkschemaregistryaacl_test.go
Labels: bug

#792 fix(kafkatopic): wait service running
  CHANGELOG.md
  controllers/common.go
  controllers/kafkatopic_controller.go
Labels: bug

#796 fix(serviceintegration): sends empty strings
  CHANGELOG.md
  controllers/common.go
  controllers/serviceintegration_controller.go
Labels: bug
